### ISSUE TITLE
Extension breaks the forum on Safari 9 and maybe old Chromium

### ISSUE THREAD

**Issue by matteocontrini** [FriendsOfFlarum/share-social#1] opened 2019-06-21 18:28 UTC
I have reports that this extension breaks the JavaScript version of the forum on some "old" browsers.

A couple of users told me that they got "Something went wrong [...]" when loading the forum, and they saw the "nojs" version.

The two browsers that the users are using are:

- Safari on iOS 9
- Samsung Internet 4.5.10 on a Samsung device

I asked the user that had the issue on the Samsung device to connect remotely to the dev tools (Samsung Internet is based on Chromium in recent versions), and he sent me this screenshot:

![immagine](https://user-images.githubusercontent.com/2164763/59943523-c091d780-9462-11e9-8420-d77582a7d66d.png)

I don't have the exact position that's causing that first syntax error, but line 1526 in that dist file is something about the share-social extension.

![immagine](https://user-images.githubusercontent.com/2164763/59943583-ea4afe80-9462-11e9-9fb7-585567b03ce1.png)

I disabled the extension and the users are not experiencing issues anymore.

I think this might be related to some modern JavaScript feature not being parsed correctly in those browsers, even though transpiling should take care of this.

**Comment by Ralkage** [comment] 2019-06-21 18:34
@matteocontrini this may be tough to replicate given those are dated versions of mobile browsers on dated OS's.

I can possibly test on my old Galaxy Tab and get back to you with an exact cause or if @datitisev ends up finding out the problem himself.

**Comment by matteocontrini** [comment] 2019-06-21 18:35
Indeed... I was looking for an APK for the Samsung browser but I can't find it 🤔

**Comment by datitisev** [comment] 2019-06-21 18:57
I was able to reproduce on Safari 5 (I don't have Safari 5 installed)... so it's definitely an old browser issue. And it's definitely share social, though I'm not sure what the issue is with the syntax.

I'm going to look a bit into it.

**Comment by datitisev** [comment] 2019-06-21 19:10
@matteocontrini Ok, so I might have fixed the issue. Can you run `composer require FriendsOfFlarum/share-social dev-master`, make sure it uses df0217f, and ask them to try again ?

The issue was some of our dependencies using code that didn't work in old browsers. I just made the compiler _not_ ignore the dependencies folder so it would work in older browsers.

**Comment by matteocontrini** [comment] 2019-06-21 19:24
I asked the user and I'll let you know as soon as he replies (kind of 😅)

Thank you!

**Comment by matteocontrini** [comment] 2019-06-21 19:54
The user tells me that the forum loads but when he taps "reply", either on a post or at the bottom of a discussion, nothing happens. I disabled the extension again to see if it works without it. It might be another unrelated issue...

**Comment by datitisev** [comment] 2019-06-21 19:57
That is an issue known to occur in IE 11, and makes sense that it occurs in other old browsers.

That is caused by flarum/markdown, and will be fixed in beta 9. See https://github.com/flarum/core/issues/1702 for updates on it.

Now that the issue is solved, I released v0.1.1, so run `composer require fof/share-social ^0.1.1` to stop using the dev version.

**Closed by datitisev** 2019-06-21 19:57 UTC
Labels: bug

**Comment by matteocontrini** [comment] 2019-06-21 20:00
Oh right, I remember. Thanks for the rapid fix!
